obs-to-odoo-resource route will fail in case of obsgroup usage and a null value
mekomsolutions/eip-routes-odoo pull request #10
Opened 2023-05-15 16:05 UTC by icrc-fdeniger

In this case, the obs value of the obsgroup observation is null.
It will produce this error in eip:

```
category=watcher-error-handler Cause: EL1011E: Method call: Attempted to call method get(java.lang.String) on null context object
```

2023-05-19 06:03 UTC, Ruhanga requested changes

2023-05-19 06:03 UTC, Ruhanga commented on src/main/resources/camel/obs/obs-to-odoo-resource.xml
> +                        <log loggingLevel="DEBUG" message="Obs has configured question concept and non null value" />
We definitely have to add tests for this. @icrc-fdeniger, you can follow some existing test examples; https://github.com/mekomsolutions/eip-routes-odoo/blob/master/src/test/java/com/mekomsolutions/eip/route/obs/ObsToOdooResourceRouteTest.java

2023-05-19 06:03 UTC, Ruhanga commented on src/main/resources/camel/obs/obs-to-odoo-resource.xml
> +                        <log loggingLevel="DEBUG" message="Skipping Obs because the question concept doesn't match any configured question or is null" />
This change will break some existing tests @icrc-fdeniger. Those will need to be aligned.

2023-05-22 09:37 UTC, icrc-fdeniger commented
Hello @Ruhanga,

I modified:

- main pom.xml to use https instead of http
- obs-to-odoo-resource.xml to add more accurate log
- Then [ObsToOdooResourceRouteTest.java](https://github.com/mekomsolutions/eip-routes-odoo/blob/master/src/test/java/com/mekomsolutions/eip/route/obs/ObsToOdooResourceRouteTest.java) to support the changes.

2023-05-25 08:13 UTC, Ruhanga commented
Thanks for the changes @icrc-fdeniger. Could you create a Jira ticket [here](https://issues.openmrs.org/projects/EIP/issues/EIP-75?filter=allopenissues) with the ERP component tag? This will makes issue documentation easy.

2023-05-25 08:50 UTC, icrc-fdeniger commented
@Ruhanga Done here : https://issues.openmrs.org/browse/EIP-131

2023-05-25 10:29 UTC, Ruhanga requested changes
I've added a few hopefully final comments @icrc-fdeniger.

2023-05-25 10:29 UTC, Ruhanga commented on src/main/resources/camel/obs/obs-to-odoo-resource.xml
> +                        <!--in case of obsgroup usage the value can be null-->
```suggestion
                        <!--Skip obs with null value, this could be an obsgroup-->
```

2023-05-25 10:29 UTC, Ruhanga commented on src/main/resources/camel/obs/obs-to-odoo-resource.xml
> +                                <log loggingLevel="DEBUG" message="Skipping obs because the value is null" />
```suggestion
                                <log loggingLevel="DEBUG" message="Skipping obs because it's value is null" />
```

2023-05-25 10:29 UTC, Ruhanga commented on src/test/java/com/mekomsolutions/eip/route/obs/ObsToOdooResourceRouteTest.java
> +		assertMessageLogged(Level.DEBUG, "Skipping obs because the value is null");
This will be updated based on the suggested change in the route.

2023-05-25 17:04 UTC, Ruhanga approved these changes
Looks good to me. @wluyima is this all ok with you?

2023-05-31 19:38 UTC, merged